[package]
name = "atomas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serde]
version = "1.0.192"
features = ["derive"]

[dependencies]
image = "0.24.7"
rand = "0.8.5"
